"""Core domain layer: entities, value objects, domain rules, and scoring specifications."""

from .ats_matcher import (
    ATSKeywordMatchResult,
    extract_keywords,
    score_ats_keywords,
)
from .gates import (
    BANNED_METRIC_PATTERNS,
    BANNED_TOOLS,
    GPA_PATTERNS,
    LATEX_LEAK_PATTERNS,
    GateResult,
    check_banned_content_gate,
    check_density_gate,
    check_gpa_gate,
    check_latex_leak_gate,
)
from .ingestion import (
    JobPosting,
    RawJobPayload,
    ScreeningQuestion,
)
from .models import (
    DEFAULT_PROFILE_PATH,
    REQUIRED_CONTACT_FIELDS,
    TAILORED_NAME,
    CompilerConfig,
    Contact,
    CourseworkMode,
    Education,
    Experience,
    Pick,
    PlanError,
    Profile,
    Project,
    Selection,
    profile_index,
    profile_to_dict,
    validate_contact,
)
from .plan import parse_plan
from .rules import MIN_BULLETS, full_selection, trim_step

__all__ = [
    "BANNED_METRIC_PATTERNS",
    "BANNED_TOOLS",
    "DEFAULT_PROFILE_PATH",
    "GPA_PATTERNS",
    "LATEX_LEAK_PATTERNS",
    "MIN_BULLETS",
    "REQUIRED_CONTACT_FIELDS",
    "TAILORED_NAME",
    "ATSKeywordMatchResult",
    "CompilerConfig",
    "Contact",
    "CourseworkMode",
    "Education",
    "Experience",
    "GateResult",
    "JobPosting",
    "Pick",
    "PlanError",
    "Profile",
    "Project",
    "RawJobPayload",
    "ScreeningQuestion",
    "Selection",
    "check_banned_content_gate",
    "check_density_gate",
    "check_gpa_gate",
    "check_latex_leak_gate",
    "extract_keywords",
    "full_selection",
    "parse_plan",
    "profile_index",
    "profile_to_dict",
    "score_ats_keywords",
    "trim_step",
    "validate_contact",
]
