"""Deterministic resume compiler contracts."""

from .models import (
    Bullet,
    CanonicalProfile,
    Contact,
    DocumentType,
    EducationEntry,
    ExperienceEntry,
    ProjectEntry,
    RenderExperience,
    RenderModel,
    RenderProject,
    SelectionPlan,
    SkillGroup,
    SkillItem,
    Target,
    TemplateSpec,
    ValidationErrorDetail,
)
from .profile import ProfileValidationError, derive_legacy_id, load_canonical_profile
from .artifacts import (
    ArtifactExportResult,
    ArtifactStore,
    InvalidPdfArtifactError,
    TexArtifactRecord,
    artifact_cache_key,
    atomic_write_bytes,
    atomic_write_text,
    canonical_profile_hash,
    pdf_validation_error,
    template_spec_hash,
)
from .compiler import (
    COMPILER_BACKEND_VERSION,
    DEFAULT_COMPILE_TIMEOUT_SECONDS,
    CompileResult,
    CompilerBackend,
)
from .renderer import RENDERER_VERSION, TexRenderer, tex_text, render_tex
from .selection import (
    PlanValidationError,
    build_render_model,
    normalize_selection_plan,
    selection_plan_artifact_json,
)
from .planner import (
    DEFAULT_PLANNER_MODEL_ID,
    PLAN_CACHE_KEY_VERSION,
    PLANNER_PROMPT_VERSION,
    PLANNER_SCHEMA_VERSION,
    GeminiPlanner,
    PlanCache,
    PlannerJsonError,
    PlannerResult,
    build_planner_prompt,
    deterministic_fallback_selection_plan,
    parse_planner_json,
    plan_cache_key,
    planner_template_spec_hash,
    raw_input_hash,
)
from .templates import BUILTIN_TEMPLATE_SPECS, get_template_spec

__all__ = [
    "BUILTIN_TEMPLATE_SPECS",
    "ArtifactExportResult",
    "ArtifactStore",
    "Bullet",
    "CanonicalProfile",
    "COMPILER_BACKEND_VERSION",
    "DEFAULT_COMPILE_TIMEOUT_SECONDS",
    "CompileResult",
    "CompilerBackend",
    "Contact",
    "DEFAULT_PLANNER_MODEL_ID",
    "DocumentType",
    "EducationEntry",
    "ExperienceEntry",
    "GeminiPlanner",
    "InvalidPdfArtifactError",
    "PLAN_CACHE_KEY_VERSION",
    "PLANNER_PROMPT_VERSION",
    "PLANNER_SCHEMA_VERSION",
    "PlanCache",
    "PlannerJsonError",
    "PlannerResult",
    "PlanValidationError",
    "ProfileValidationError",
    "ProjectEntry",
    "RENDERER_VERSION",
    "RenderExperience",
    "RenderModel",
    "RenderProject",
    "SelectionPlan",
    "SkillGroup",
    "SkillItem",
    "Target",
    "TemplateSpec",
    "TexArtifactRecord",
    "TexRenderer",
    "ValidationErrorDetail",
    "artifact_cache_key",
    "atomic_write_bytes",
    "atomic_write_text",
    "build_render_model",
    "build_planner_prompt",
    "canonical_profile_hash",
    "deterministic_fallback_selection_plan",
    "derive_legacy_id",
    "tex_text",
    "get_template_spec",
    "load_canonical_profile",
    "normalize_selection_plan",
    "parse_planner_json",
    "pdf_validation_error",
    "plan_cache_key",
    "planner_template_spec_hash",
    "raw_input_hash",
    "render_tex",
    "selection_plan_artifact_json",
    "template_spec_hash",
]
